# Learn Posture

use machine learning to recognize robot's posture (following the example in [scikit-learn-intro.ipynb](./scikit-learn-intro.ipynb) )

## 1. Data collection

We have colleceted data before, you need to add new data if you want to add new posture.

* the dateset are in *robot_pose_data* folder
* each file contains the data belongs to this posture, e.g. the data in *Back* file are collected when robot was in "Back" posture
* the data file can be load by ```pickle```, e.g. ```pickle.load(open('Back'))```, the data is a list of feature data
* the features (e.g. each row of the data) are ['LHipYawPitch', 'LHipRoll', 'LHipPitch', 'LKneePitch', 'RHipYawPitch', 'RHipRoll', 'RHipPitch', 'RKneePitch', 'AngleX', 'AngleY'], where 'AngleX' and 'AngleY' are body angle (e.g. ```Perception.imu```) and others are joint angles.

## 2. Data preprocessing

In [1]:
%pylab inline
import pickle
from os import listdir, path
import numpy as np
from sklearn import svm, metrics

ROBOT_POSE_DATA_DIR = 'robot_pose_data'

Populating the interactive namespace from numpy and matplotlib


In [2]:
classes = listdir(ROBOT_POSE_DATA_DIR)
print classes

['Knee', 'Right', 'Stand', 'Left', 'HeadBack', 'Frog', 'Crouch', 'Sit', 'StandInit', 'Back', 'Belly']


In [3]:
def load_pose_data(i):
    '''load pose data from file'''
    data = []
    target = []
    # YOUR CODE HERE
  
    filename = path.join(ROBOT_POSE_DATA_DIR, classes[i])
    data = pickle.load(open(filename))
    target = [i] * len(data)
    
    #print "Data: %s" % data
    #print "Target: %s" % target
   
    return data, target

In [4]:
# load all the data
all_data = []
all_target = []
# YOUR CODE HERE

for i in range(len(classes)):
    all_data.append(load_pose_data(i)[0])
    all_target.append(load_pose_data(i)[1])    

print 'total number of data', len(all_data)

total number of data 11


In [5]:
# shuffule data
permutation = np.random.permutation(len(all_data))
n_training_data = int(len(all_data) * 0.7)
training_data = permutation[:n_training_data]

## 3. Learn on training data

In scikit-learn, an estimator for classification is a Python object that implements the methods fit(X, y) and predict(T). An example of an estimator is the class sklearn.svm.SVC that implements support vector classification.

In [6]:
clf = svm.SVC(gamma=0.001, C=100.)

### learning

In [7]:
# YOUR CODE HERE
matrix = []
vector = []

# reshape data to a matrix DxN
# - D is the data
# - N is amount of data
for i in range(len(all_data)): 
    for j in range (len(all_data[i])):
        matrix.append(np.array(all_data[i][j]).flatten())
        #print (np.array(all_data[i][j]).flatten())
      

# reshape target to a vector N
for i in range(len(all_target)): 
    for j in range (len(all_target[i])):
        vector.append(all_target[i][j])

matrix = np.array(matrix)
vector = np.array(vector).flatten()

#print matrix.shape
#print vector.shape

clf.fit(matrix, vector)

SVC(C=100.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma=0.001, kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

### predicting

In [8]:
clf.predict(all_data[-1]), all_target[-1]

(array([10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10,
        10, 10]),
 [10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10])

In [9]:
def evaluate(expected, predicted):
    print("Classification report:\n%s\n" % metrics.classification_report(expected, predicted))

    print("Confusion matrix:\n%s" % metrics.confusion_matrix(expected, predicted))

In [21]:
expected = []
predicted = []
# YOUR CODE HERE
from scipy import sparse

for i in all_data:
    predicted.append(clf.predict(i).tolist())
    
for j in all_target:
    expected.append(j)

#print predicted
#print expected

for i in range(len(expected)):
    evaluate(expected[i],predicted[i])

Classification report:
             precision    recall  f1-score   support

          0       1.00      1.00      1.00        10

avg / total       1.00      1.00      1.00        10


Confusion matrix:
[[10]]
Classification report:
             precision    recall  f1-score   support

          1       1.00      0.91      0.95        11
          6       0.00      0.00      0.00         0

avg / total       1.00      0.91      0.95        11


Confusion matrix:
[[10  1]
 [ 0  0]]
Classification report:
             precision    recall  f1-score   support

          2       1.00      1.00      1.00        11

avg / total       1.00      1.00      1.00        11


Confusion matrix:
[[11]]
Classification report:
             precision    recall  f1-score   support

          3       1.00      1.00      1.00        20

avg / total       1.00      1.00      1.00        20


Confusion matrix:
[[20]]
Classification report:
             precision    recall  f1-score   support

          4   

## 4. Evaluate on the test data

In [23]:
expected = []
predicted = []
# YOUR CODE HERE
for i in all_data:
    predicted.append(clf.predict(i).tolist())
    
for j in all_target:
    expected.append(j)
    
for i in range(len(expected)):
    evaluate(expected[i],predicted[i])

Classification report:
             precision    recall  f1-score   support

          0       1.00      1.00      1.00        10

avg / total       1.00      1.00      1.00        10


Confusion matrix:
[[10]]
Classification report:
             precision    recall  f1-score   support

          1       1.00      0.91      0.95        11
          6       0.00      0.00      0.00         0

avg / total       1.00      0.91      0.95        11


Confusion matrix:
[[10  1]
 [ 0  0]]
Classification report:
             precision    recall  f1-score   support

          2       1.00      1.00      1.00        11

avg / total       1.00      1.00      1.00        11


Confusion matrix:
[[11]]
Classification report:
             precision    recall  f1-score   support

          3       1.00      1.00      1.00        20

avg / total       1.00      1.00      1.00        20


Confusion matrix:
[[20]]
Classification report:
             precision    recall  f1-score   support

          4   

## 5. Deploy to the real system

We can simple use `pickle` module to serialize the trained classifier.

In [24]:
import pickle
ROBOT_POSE_CLF = 'robot_pose.pkl'
pickle.dump(clf, open(ROBOT_POSE_CLF, 'w'))

Then, in the application we can load the trained classifier again.

In [25]:
clf2 = pickle.load(open(ROBOT_POSE_CLF))
clf2.predict(all_data[-1]), all_target[-1]

(array([10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10,
        10, 10]),
 [10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10])